### ISSUE TITLE
I2C Communication to Buttons does not work: Nix(ENXIO)

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#51] opened 2023-08-03 17:35 UTC
Testing opensesame on a board without the MOD-IO2 module causes the following Error.

```bash
thread 'main' panicked at 'I2C Communication to Buttons does not work: Nix(ENXIO)', src/buttons.rs:142:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::expect
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1070:23
   4: opensesame::buttons::Buttons::init
             at ./src/buttons.rs:140:3
   5: opensesame::buttons::Buttons::new
             at ./src/buttons.rs:135:3
   6: opensesame::main
             at ./src/main.rs:296:20
   7: core::ops::function::FnOnce::call_once
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Maybe we should set some variables to enable and disable modules in opensesame. As I have seen `buttons` is widely used in the source, so it's hard to disable it without causing other errors.

**Comment by markus2330** [comment] 2023-08-03 18:12
It is already possible to disable some modules. Disabling the buttons is currently only possible by enabling sensors, which --- I agree --- is a weird hack. When we introduce more and more Tokio, we can also create smaller modules.

But: we should keep the current uniform way of using Elektra's configs `<module>/enable` to enable modules. We can use environment variables and command-line arguments also via Elektra, maybe @flo91 will work on that.  #28

**Comment by markus2330** [comment] 2023-08-04 10:01
> How do I enable sensors?

spec and code should give such answers :wink:

**Comment by fel115** [comment] 2023-08-04 11:28
> > How do I enable sensors?
> 
> spec and code should give such answers 😉

Ahhh eh

**Comment by markus2330** [comment] 2023-08-04 17:02
I created /home/olimex/.config/opensesame.toml using Ansible, can you please add the additional config needed for the weatherstation?  (sensor mode is already active)

**Comment by markus2330** [comment] 2023-08-04 17:34
I get this error above even if `user:/sw/libelektra/opensesame/#0/current/sensors/#0/loc` is present.

Seems like there is some regression.

**Comment by markus2330** [comment] 2023-10-15 16:27
Seems to be fixed now.

**Closed by markus2330** 2023-10-15 16:27 UTC
