### ISSUE TITLE
Env - warn on fast raising values, next to MQ135 (temperature, CO2, VOC, Pressure)

### ISSUE THREAD

**Issue by fel115** [ElektraInitiative/opensesame#71] opened 2023-08-21 16:33 UTC
@markus2330 How is the MQ135 connected via the `/dev/ttyACM0`? And where should this function be implemented, in the environment.rs or mod_ir_temp.rs?

**Comment by markus2330** [comment] 2023-08-22 13:01
For MQ135 it is already implemented, see src/sensors.rs line 154. The idea is to do the same for mod-env and mod-ir.

The idea is to warn on very fast changing values, which could be caused by direct sunshine or also fire.

**Comment by fel115** [comment] 2023-08-23 08:22
Ok, this needs to be implemented for MOD-IR-TEMP and MOD-ENV. Is it a requirement to use the Exponential Moving Average?

**Comment by markus2330** [comment] 2023-10-14 14:17
@fel115 do you already have a fix for this?

**Comment by fel115** [comment] 2023-10-18 14:39
Not implemented now

**Closed** 2023-10-19 10:00 UTC
Labels: enhancement
